"""create rasters table

Revision ID: 278ddb9ffaae
Revises: db398818c05b
Create Date: 2026-08-05 05:58:41.470378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278ddb9ffaae'
down_revision: Union[str, Sequence[str], None] = 'db398818c05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rasters',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_raster_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('DEM', 'SATELLITE', 'LAND_COVER', 'SLOPE', 'ASPECT', 'HILLSHADE', 'PREDICTION', 'UNCERTAINTY', 'OTHER', name='rastertype'), nullable=False),
    sa.Column('source', sa.Enum('UPLOADED', 'GENERATED', 'IMPORTED', name='rastersource'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'READY', 'PROCESSING', 'FAILED', name='rasterstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('crs', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('band_count', sa.Integer(), nullable=True),
    sa.Column('pixel_size_x', sa.Float(), nullable=True),
    sa.Column('pixel_size_y', sa.Float(), nullable=True),
    sa.Column('min_x', sa.Float(), nullable=True),
    sa.Column('min_y', sa.Float(), nullable=True),
    sa.Column('max_x', sa.Float(), nullable=True),
    sa.Column('max_y', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_raster_id'], ['rasters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_rasters_parent_raster_id'), 'rasters', ['parent_raster_id'], unique=False)
    op.create_index(op.f('ix_rasters_project_id'), 'rasters', ['project_id'], unique=False)
    op.create_index('ix_rasters_project_parent', 'rasters', ['project_id', 'parent_raster_id'], unique=False)
    op.create_index('ix_rasters_project_status', 'rasters', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rasters_project_status', table_name='rasters')
    op.drop_index('ix_rasters_project_parent', table_name='rasters')
    op.drop_index(op.f('ix_rasters_project_id'), table_name='rasters')
    op.drop_index(op.f('ix_rasters_parent_raster_id'), table_name='rasters')
    op.drop_table('rasters')
    # ### end Alembic commands ###
