"""Sync DB with processing job model changes

Revision ID: 411848942447
Revises: b06321db454b
Create Date: 2026-08-07 07:55:00.161267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411848942447'
down_revision: Union[str, Sequence[str], None] = 'b06321db454b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('executor', sa.String(length=32), nullable=False))
    op.add_column('processing_jobs', sa.Column('parameters', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'rasters', ['file_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rasters', type_='unique')
    op.drop_column('processing_jobs', 'parameters')
    op.drop_column('processing_jobs', 'executor')
    # ### end Alembic commands ###
