"""add_multi_input_processing_lineage

Revision ID: 4f88d3b9a55e
Revises: ad2cdb59c3d2
Create Date: 2026-08-10 14:06:33.539732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f88d3b9a55e'
down_revision: Union[str, Sequence[str], None] = 'ad2cdb59c3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raster_lineage',
    sa.Column('child_raster_id', sa.Integer(), nullable=False),
    sa.Column('parent_raster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_raster_id'], ['rasters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_raster_id'], ['rasters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_raster_id', 'parent_raster_id')
    )
    op.add_column('processing_jobs', sa.Column('project_id', sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE processing_jobs
        SET project_id = rasters.project_id
        FROM rasters
        WHERE processing_jobs.raster_id = rasters.id
        """
    )
    op.alter_column('processing_jobs', 'project_id', nullable=False)

    op.alter_column('processing_jobs', 'raster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_processing_jobs_project_id'), 'processing_jobs', ['project_id'], unique=False)
    op.create_foreign_key('fk_processing_jobs_project_id_projects', 'processing_jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_processing_jobs_project_id_projects', 'processing_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_processing_jobs_project_id'), table_name='processing_jobs')
    op.alter_column('processing_jobs', 'raster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('processing_jobs', 'project_id')
    op.drop_table('raster_lineage')
    # ### end Alembic commands ###
