"""add raster provenance

Revision ID: 75305d877b28
Revises: db13f16caadc
Create Date: 2026-08-07 13:59:37.858372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75305d877b28'
down_revision: Union[str, Sequence[str], None] = 'db13f16caadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rasters', sa.Column('processor', sa.Enum('METADATA', 'HILLSHADE', 'SLOPE', 'ASPECT', 'CLIP', 'MERGE', 'REPROJECT', 'PREDICTION', 'UNCERTAINTY', 'CUSTOM', name='processor_type'), nullable=True))
    op.add_column('rasters', sa.Column('processor_version', sa.String(length=32), nullable=True))
    op.add_column('rasters', sa.Column('processing_parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rasters', 'processing_parameters')
    op.drop_column('rasters', 'processor_version')
    op.drop_column('rasters', 'processor')
    # ### end Alembic commands ###
