"""create vector layers table

Revision ID: ad2cdb59c3d2
Revises: 0d362aad239d
Create Date: 2026-08-09 16:32:53.265480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ad2cdb59c3d2'
down_revision: Union[str, Sequence[str], None] = '0d362aad239d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_layers',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_raster_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artifact_type', sa.Enum('CONTOUR', 'OTHER', name='vectortype'), nullable=False),
    sa.Column('status', sa.Enum('READY', 'PROCESSING', 'FAILED', name='vectorstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('geometry_type', sa.String(length=64), nullable=True),
    sa.Column('crs', sa.String(length=64), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('processor', postgresql.ENUM('METADATA', 'HILLSHADE', 'SLOPE', 'ASPECT', 'COLOR_RELIEF', 'CLIP', 'MERGE', 'REPROJECT', 'PREDICTION', 'UNCERTAINTY', 'CUSTOM', name='processor_type', create_type=False), nullable=True),
    sa.Column('processor_version', sa.String(length=32), nullable=True),
    sa.Column('processing_parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_raster_id'], ['rasters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_vector_layers_parent_raster_id'), 'vector_layers', ['parent_raster_id'], unique=False)
    op.create_index(op.f('ix_vector_layers_project_id'), 'vector_layers', ['project_id'], unique=False)
    op.create_index('ix_vector_layers_project_parent', 'vector_layers', ['project_id', 'parent_raster_id'], unique=False)
    op.create_index('ix_vector_layers_project_status', 'vector_layers', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vector_layers_project_status', table_name='vector_layers')
    op.drop_index('ix_vector_layers_project_parent', table_name='vector_layers')
    op.drop_index(op.f('ix_vector_layers_project_id'), table_name='vector_layers')
    op.drop_index(op.f('ix_vector_layers_parent_raster_id'), table_name='vector_layers')
    op.drop_table('vector_layers')
    
    # Drop vector enums created in upgrade
    sa.Enum(name='vectortype').drop(op.get_bind())
    sa.Enum(name='vectorstatus').drop(op.get_bind())
    # ### end Alembic commands ###
