"""Add cancel_requested_at and CANCELLING status

Revision ID: db13f16caadc
Revises: 411848942447
Create Date: 2026-08-07 13:02:50.041057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db13f16caadc'
down_revision: Union[str, Sequence[str], None] = '411848942447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE processing_status ADD VALUE IF NOT EXISTS 'CANCELLING'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'cancel_requested_at')
    # ### end Alembic commands ###
